# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import qgis_plugin_repository.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QgisPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('qgisMinimumVersion', models.CharField(max_length=20)),
                ('qgisMaximumVersion', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('changelog', models.CharField(blank=True, max_length=255, null=True)),
                ('experimental', models.BooleanField(default=False)),
                ('deprecated', models.BooleanField(default=False)),
                ('tags', models.CharField(max_length=255)),
                ('homepage', models.CharField(blank=True, max_length=100, null=True)),
                ('repository', models.CharField(max_length=100)),
                ('tracker', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(storage=qgis_plugin_repository.models.OverwriteStorage(), upload_to='qgis_plugins')),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
