# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import qgis_plugin_repository.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QgisPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('version', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('about', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(storage=qgis_plugin_repository.models.OverwriteStorage, upload_to='qgis_plugins')),
                ('is_trusted', models.BooleanField(default=False)),
                ('qgis_minimum_version', models.CharField(max_length=20)),
                ('qgis_maximum_version', models.CharField(max_length=20)),
                ('homepage', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('create_date', models.DateField()),
                ('update_date', models.DateField()),
                ('is_experimental', models.BooleanField(default=False)),
                ('is_deprecated', models.BooleanField(default=False)),
            ],
        ),
    ]
