# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import qgis_plugin_repository.models


class Migration(migrations.Migration):

    dependencies = [
        ('qgis_plugin_repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qgisplugin',
            name='file',
            field=models.FileField(storage=qgis_plugin_repository.models.OverwriteStorage(), upload_to='qgis_plugins'),
        ),
        migrations.AlterField(
            model_name='qgisplugin',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
